import { useEffect, useMemo, useState } from 'react';
import type { ChangeEvent } from 'react';
import { emptyData, loadData, saveData } from './data';
import type { AppData, Exercise, ExerciseLog, Program, SetLog, WeighIn, Workout } from './types';

type Tab = 'home' | 'history' | 'profile';
const uid = () => crypto.randomUUID();
const newSet = (): SetLog => ({ id: uid(), weight: 0, reps: 0, completed: false });
const newLog = (exercise: Exercise): ExerciseLog => ({ exercise, sets: [newSet(), newSet(), newSet()] });
const volume = (workout: Workout) => workout.exercises.flatMap(x => x.sets).filter(s => s.completed).reduce((n, s) => n + s.weight * s.reps, 0);
const fmt = (n: number) => new Intl.NumberFormat().format(n);

export default function App() {
  const [data, setData] = useState<AppData>(loadData);
  const [tab, setTab] = useState<Tab>('home');
  const [active, setActive] = useState<Workout | null>(null);
  const [editingProgram, setEditingProgram] = useState<Program | null>(null);
  useEffect(() => saveData(data), [data]);

  const startWorkout = (p: Program) => setActive({ id: uid(), programId: p.id, name: p.name, date: new Date().toISOString(), exercises: p.exercises.map(newLog) });
  const lastFor = (exerciseId: string) => data.history.find(w => w.exercises.some(e => e.exercise.id === exerciseId))?.exercises.find(e => e.exercise.id === exerciseId);
  const updateActive = (fn: (w: Workout) => Workout) => setActive(w => w ? fn(w) : w);
  const finishWorkout = () => { if (!active) return; setData(d => ({ ...d, history: [active, ...d.history] })); setActive(null); setTab('history'); };
  const updatePrograms = (programs: Program[]) => setData(d => ({ ...d, programs }));

  if (active) return <WorkoutScreen workout={active} lastFor={lastFor} update={updateActive} finish={finishWorkout} cancel={() => setActive(null)} />;
  if (editingProgram) return <ProgramEditor program={editingProgram} save={(p) => { updatePrograms(data.programs.map(x => x.id === p.id ? p : x)); setEditingProgram(null); }} back={() => setEditingProgram(null)} />;
  return <main className="app">
    <header><div className="brand"><span className="brand-mark">⌁</span> PRO FIT</div><span className="tag">TRAIN SMART</span></header>
    {tab === 'home' && <Home programs={data.programs} history={data.history} onStart={startWorkout} onEdit={setEditingProgram} onNew={() => setEditingProgram({ id: uid(), name: 'New workout', exercises: [] })} />}
    {tab === 'history' && <History history={data.history} />}
    {tab === 'profile' && <Profile profile={data.profile} history={data.history} weightHistory={data.weightHistory} save={(profile) => setData(d => ({ ...d, profile }))} addWeighIn={(weight) => setData(d => ({ ...d, profile: { ...d.profile, bodyWeight: String(weight) }, weightHistory: [{ id: uid(), date: new Date().toISOString(), weight }, ...d.weightHistory] }))} reset={() => { if (confirm('Reset all PRO FIT data?')) setData(emptyData()); }} />}
    <nav><button className={tab==='home'?'on':''} onClick={() => setTab('home')}><span>⌂</span>Workouts</button><button className={tab==='history'?'on':''} onClick={() => setTab('history')}><span>◷</span>History</button><button className={tab==='profile'?'on':''} onClick={() => setTab('profile')}><span>◎</span>Profile</button></nav>
  </main>;
}

function Home({ programs, history, onStart, onEdit, onNew }: { programs: Program[]; history: Workout[]; onStart: (p: Program) => void; onEdit: (p: Program) => void; onNew: () => void }) { return <section className="screen"><div className="eyebrow">YOUR TRAINING</div><h1>Ready to get stronger?</h1><p className="muted">Choose a workout and log your progress.</p><div className="section-row"><h2>Programs</h2><button className="text-button" onClick={onNew}>+ New</button></div><div className="program-list">{programs.map(p => <article className="program-card" key={p.id}><button className="card-main" onClick={() => onStart(p)}><span className="program-icon">{p.name[0]}</span><span><strong>{p.name}</strong><small>{p.exercises.length} exercises</small></span><b>Start ›</b></button><button className="edit" aria-label={'Edit ' + p.name} onClick={() => onEdit(p)}>⋯</button></article>)}</div>{history[0] && <><div className="section-row"><h2>Last session</h2></div><div className="last-session"><strong>{history[0].name}</strong><span>{new Date(history[0].date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} · {fmt(volume(history[0]))} kg volume</span></div></>}</section> }

function WorkoutScreen({ workout, lastFor, update, finish, cancel }: { workout: Workout; lastFor: (id: string) => ExerciseLog | undefined; update: (fn: (w: Workout) => Workout) => void; finish: () => void; cancel: () => void }) {
  const [exerciseIndex, setExerciseIndex] = useState(0);
  const updateSet = (ei: number, si: number, patch: Partial<SetLog>) => update(w => ({ ...w, exercises: w.exercises.map((e, i) => i !== ei ? e : { ...e, sets: e.sets.map((s, j) => j !== si ? s : { ...s, ...patch }) }) }));
  const addSet = (ei: number) => update(w => ({ ...w, exercises: w.exercises.map((e, i) => i === ei ? { ...e, sets: [...e.sets, newSet()] } : e) }));
  const deleteSet = (ei: number, si: number) => update(w => ({ ...w, exercises: w.exercises.map((e, i) => i === ei ? { ...e, sets: e.sets.filter((_, j) => j !== si) } : e) }));
  const log = workout.exercises[exerciseIndex];
  return <main className="app workout"><header><button className="back" onClick={cancel}>‹</button><div><div className="eyebrow">ACTIVE WORKOUT · {exerciseIndex + 1}/{workout.exercises.length}</div><h2>{workout.name}</h2></div><button className="finish" onClick={finish}>Finish</button></header><section className="screen"><ExerciseCard log={log} last={lastFor(log.exercise.id)} updateSet={(si,p) => updateSet(exerciseIndex,si,p)} add={() => addSet(exerciseIndex)} remove={(si) => deleteSet(exerciseIndex,si)} /><div className="exercise-pager"><button disabled={exerciseIndex === 0} onClick={() => setExerciseIndex(i => i - 1)}>Previous</button>{exerciseIndex < workout.exercises.length - 1 ? <button className="next" onClick={() => setExerciseIndex(i => i + 1)}>Next exercise</button> : <button className="finish-wide" onClick={finish}>Finish workout</button>}</div></section></main>;
}

function ExerciseCard({ log, last, updateSet, add, remove }: { log: ExerciseLog; last?: ExerciseLog; updateSet: (i: number, patch: Partial<SetLog>) => void; add: () => void; remove: (i: number) => void }) { const completed = log.sets.length > 0 && log.sets.every(s => s.completed); const topLast = last?.sets.filter(s => s.completed).sort((a,b) => b.weight*b.reps-a.weight*a.reps)[0]; const suggestion = topLast && completed && log.sets.every(s => s.reps >= topLast.reps) ? `Try ${topLast.weight % 5 === 0 ? topLast.weight + 2.5 : topLast.weight + 2.5} kg next time` : null; return <article className="exercise"><div className="exercise-head"><div><h2>{log.exercise.name}</h2><span className="muscle">{log.exercise.muscle}</span></div>{completed && <span className="done">✓ Done</span>}</div>{topLast ? <div className="last">Last time <b>{topLast.weight} kg × {topLast.reps}</b>{suggestion && <em>↗ {suggestion}</em>}</div> : <div className="last">No previous performance yet — set your baseline.</div>}<div className="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>DONE</span></div>{log.sets.map((s,i) => <div className="set-row" key={s.id}><span className="set-number">{i+1}</span><input inputMode="decimal" aria-label="Weight" value={s.weight || ''} placeholder="0" onChange={e => updateSet(i, { weight: Number(e.target.value) })}/><input inputMode="numeric" aria-label="Reps" value={s.reps || ''} placeholder="0" onChange={e => updateSet(i, { reps: Number(e.target.value) })}/><button className={'check '+(s.completed?'checked':'')} aria-label="Mark completed" onClick={() => updateSet(i, { completed: !s.completed })}>{s.completed ? '✓' : ''}</button><button className="remove" onClick={() => remove(i)} aria-label="Remove set">×</button></div>)}<button className="add-set" onClick={add}>+ Add set</button></article>; }

function History({ history }: { history: Workout[] }) { return <section className="screen"><div className="eyebrow">YOUR PROGRESS</div><h1>Workout history</h1>{history.length === 0 ? <div className="empty"><span>◷</span><h2>No sessions yet</h2><p>Complete your first workout to see it here.</p></div> : <div className="history-list">{history.map(w => <article className="history-card" key={w.id}><div><h2>{w.name}</h2><p>{new Date(w.date).toLocaleDateString(undefined,{weekday:'short', month:'short',day:'numeric'})} · {w.exercises.filter(e=>e.sets.some(s=>s.completed)).length} exercises</p></div><strong>{fmt(volume(w))}<small> kg</small></strong></article>)}</div>}</section> }

function Profile({ profile, history, weightHistory, save, addWeighIn, reset }: { profile: AppData['profile']; history: Workout[]; weightHistory: WeighIn[]; save: (p: AppData['profile']) => void; addWeighIn: (weight: number) => void; reset: () => void }) {
  const [weighIn, setWeighIn] = useState('');
  const field = (key: keyof AppData['profile'], label: string, placeholder: string, type = 'text') => <label>{label}<input type={type} inputMode={type === 'number' ? 'decimal' : undefined} value={profile[key]} placeholder={placeholder} onChange={e => save({ ...profile, [key]: e.target.value })}/></label>;
  const current = Number(profile.bodyWeight); const target = Number(profile.targetWeight); const remaining = target && current ? Math.abs(target - current) : 0;
  const totalVolume = history.reduce((sum, workout) => sum + volume(workout), 0);
  const completedSets = history.flatMap(w => w.exercises).flatMap(e => e.sets).filter(s => s.completed).length;
  const photoChange = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 640 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); const context = canvas.getContext('2d'); if (!context) return; context.drawImage(image, 0, 0, canvas.width, canvas.height); save({ ...profile, photo: canvas.toDataURL('image/jpeg', 0.82) }); }; image.src = String(reader.result || ''); }; reader.readAsDataURL(file); };
  const add = () => { const value = Number(weighIn); if (value > 0) { addWeighIn(value); setWeighIn(''); } };
  return <section className="screen profile-screen"><div className="profile-hero"><label className="avatar">{profile.photo ? <img src={profile.photo} alt="Your profile"/> : <span>{profile.name ? profile.name[0].toUpperCase() : 'P'}</span>}<input type="file" accept="image/*" onChange={photoChange}/><b>Change</b></label><div><div className="eyebrow">ATHLETE PROFILE</div><h1>{profile.name || 'Your profile'}</h1><p className="muted">Your progress, in one place.</p></div></div><div className="profile-card">{field('name','Name','e.g. Mohamed')}{field('age','Age','e.g. 25','number')}{field('bodyWeight','Current weight','e.g. 80 kg','number')}{field('targetWeight','Target weight','e.g. 75 kg','number')}{field('height','Height','e.g. 180 cm','number')}<label>Goal<select value={profile.goal} onChange={e => save({ ...profile, goal:e.target.value })}><option>Build muscle</option><option>Get stronger</option><option>Lose fat</option><option>Maintain fitness</option></select></label></div><section className="goal-card"><div><span>YOUR TARGET</span><strong>{target ? `${target} kg` : 'Set a target'}</strong></div><p>{remaining ? `${remaining.toFixed(1)} kg ${target > current ? 'to gain' : 'to lose'} to reach your target.` : 'Add your current and target weight to track progress.'}</p></section><div className="section-row"><h2>Weight trend</h2><span className="muted">{weightHistory.length} check-ins</span></div><WeightChart entries={weightHistory} target={target}/><div className="weigh-in"><input inputMode="decimal" value={weighIn} placeholder="Log today’s weight (kg)" onChange={e => setWeighIn(e.target.value)}/><button onClick={add}>Log</button></div><div className="section-row"><h2>Analytics</h2></div><div className="analytics-grid"><div><span>Sessions</span><strong>{history.length}</strong></div><div><span>Completed sets</span><strong>{completedSets}</strong></div><div><span>Total volume</span><strong>{fmt(totalVolume)}<small> kg</small></strong></div></div><div className="section-row"><h2>Insights</h2></div><div className="insights"><p>{history.length ? `You have logged ${history.length} session${history.length === 1 ? '' : 's'}. Keep consistency as your first win.` : 'Start a workout to unlock training insights.'}</p>{target && current && <p>{profile.goal === 'Lose fat' ? `Your target is ${remaining.toFixed(1)} kg away. A steady, sustainable trend matters most.` : `You are ${remaining.toFixed(1)} kg away from your target. Pair your training with consistent nutrition.`}</p>}{weightHistory.length >= 2 && <p>Your latest logged weight is {weightHistory[0].weight} kg. The chart will grow with every check-in.</p>}</div><p className="saved">Your photo and all progress data stay on this device.</p><button className="danger" onClick={reset}>Reset all local data</button></section>
}

function WeightChart({ entries, target }: { entries: WeighIn[]; target: number }) { const data = [...entries].reverse().slice(-8); if (!data.length) return <div className="chart-empty">Log a weigh-in to start your weight chart.</div>; const values = [...data.map(x => x.weight), ...(target ? [target] : [])]; const low = Math.min(...values) - 1; const high = Math.max(...values) + 1; const x = (i: number) => data.length === 1 ? 160 : 20 + (i * 280) / (data.length - 1); const y = (weight: number) => 112 - ((weight - low) / (high - low)) * 92; const line = data.map((point, i) => `${i ? 'L' : 'M'}${x(i)},${y(point.weight)}`).join(' '); return <div className="weight-chart"><svg viewBox="0 0 320 140" role="img" aria-label="Weight trend in kilograms"><path className="chart-grid" d="M20 20H300M20 66H300M20 112H300"/>{target > 0 && <path className="chart-target" d={`M20 ${y(target)}H300`}/>}<path className="chart-line" d={line}/>{data.map((point, i) => <circle key={point.id} className="chart-dot" cx={x(i)} cy={y(point.weight)} r="5"/>)}<text x="20" y="132">{data[0].weight} kg</text><text x="300" y="132" textAnchor="end">{data[data.length - 1].weight} kg</text></svg>{target > 0 && <span className="chart-target-label">Target {target} kg</span>}</div> }

function ProgramEditor({ program, save, back }: { program: Program; save: (p: Program) => void; back: () => void }) { const [draft, setDraft] = useState(program); const updateExercise = (i: number, patch: Partial<Exercise>) => setDraft(p => ({...p, exercises:p.exercises.map((e,j)=>j===i?{...e,...patch}:e)})); return <main className="app"><header><button className="back" onClick={back}>‹</button><h2>Edit workout</h2><button className="finish" onClick={() => save(draft)}>Save</button></header><section className="screen editor"><label>Workout name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><h2>Exercises</h2>{draft.exercises.map((e,i)=><div className="edit-exercise" key={e.id}><input value={e.name} onChange={x=>updateExercise(i,{name:x.target.value})}/><input value={e.muscle} onChange={x=>updateExercise(i,{muscle:x.target.value})}/><button onClick={()=>setDraft({...draft,exercises:draft.exercises.filter((_,j)=>j!==i)})}>×</button></div>)}<button className="add-set" onClick={()=>setDraft({...draft,exercises:[...draft.exercises,{id:uid(),name:'New exercise',muscle:'Other',notes:''}]})}>+ Add exercise</button></section></main> }
